### ISSUE TITLE
How to reproduce the comparison of IS, SCS, ID and SIFID indicators in the paper?

### ISSUE THREAD

**Issue by AbrahamHermes** [Picsart-AI-Research/IPL-Zero-Shot-Generative-Model-Adaptation#11]
First of all, thank you for your wonderful research!
When I was studying your article, I found that you did not disclose the document of indicator evaluation. I have a few questions I'd like to ask you.
First, would you consider uploading the code for metrics evaluation?Did you get the marks by placing your original and produced images in the models of other papers?
 Second, I was wondering if you used the same photo on github to evaluate the metrics? Because I noticed that you used 3 images from the web in the SIFID indicator.
I am looking forward to your reply, which is of great significance to my study of this paper.

**Comment by JiayiGuo821** [comment]
Hi @AbrahamRebirth.
We compute IS, SCS, ID and SIFID following [inception-score-pytorch](https://github.com/sbarratt/inception-score-pytorch), [RSSA](https://github.com/StevenShaw1999/RSSA), [DiffusionCLIP](https://github.com/gwang-kim/DiffusionCLIP) and [SinGAN](https://github.com/tamarott/SinGAN).

**Comment by AbrahamHermes** [comment]
Thank you for your reply. I tried to reproduce the qualitative analysis in the paper, but I still encountered difficulties. Maybe my ability is not enough to reproduce it, so I decided to stop here. Thanks again for your reply. I learned a lot from reading your paper.

**Comment by JiayiGuo821** [comment]
Thanks! Feel free to contact me if there is any further questions.
