### ISSUE TITLE
What is the experiment setting of evaluate SIFID?

### ISSUE THREAD

**Issue by Guimeng-Leo-Liu** [Picsart-AI-Research/IPL-Zero-Shot-Generative-Model-Adaptation#3]
Since SIFID was originally conducted for one reference real image and a correspond generated image, I wonder how to obtain the "correspond" generated image in IPL to compute the SIFID with the reference image, or the "correspond" generated image is just a image generated by random latent code in the finetuned model?

**Comment by JiayiGuo821** [comment]
Yes, here we used randomly generated images to compute the SIFID score. For each reference image, we reported the average score using 5k generated images.
