### ISSUE TITLE
Wondering about Recon 1, Recon 2 and Recon 3 of Figure 5

### ISSUE THREAD

**Issue by bonjour-npy** [Picsart-AI-Research/IPL-Zero-Shot-Generative-Model-Adaptation#8]
Thank you for your outstanding work, and Happy New Year.

It seems that Recon1, Recon2, and Recon3 mentioned in Figure 5, represent the latent codes of real-world images generated by Restyle, DDIM, and diffusion autoencoders, respectively.

So I'm wondering that whether the images labeled as Recon 1~3 in the paper were re-generated from these latent codes using the respective models?
![image](https://github.com/Picsart-AI-Research/IPL-Zero-Shot-Generative-Model-Adaptation/assets/73021573/96e5d138-bde7-4acf-9f8a-81560cb89d56)

**Comment by JiayiGuo821** [comment]
@bonjour-npy Yes, here "inversion results" are the inversion and reconstruction results from respective models
